# Generated by Django 5.1.6 on 2025-03-03 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Customer',
            new_name='customer',
        ),
    ]
